import { Solution } from '../../models/solution.model';

/**
 * Hero illustrations are sourced verbatim from tenxerp.com's Landing-Business assets.
 * Six base illustrations exist; we map each module to the closest semantic match.
 */
const HR = 'images/solutions/HR-Features.png';
const POWER = 'images/solutions/Powerful-Features.png';
const CONTRACT = 'images/solutions/Contract-Management.png';
const FLEET = 'images/solutions/Fleet-Management.png';
const PROPERTY = 'images/solutions/Property-Solutions.png';
const RETAIL = 'images/solutions/Retail-Solutions.png';

const HERO: Record<number, string> = {
  1: POWER,    // Financial Management
  2: RETAIL,   // Inventory
  3: RETAIL,   // Sales & Distribution
  4: CONTRACT, // Purchase & Procurement
  5: POWER,    // Manufacturing
  6: FLEET,    // Warehouse Management
  7: HR,       // HR & Payroll
  8: HR,       // CRM
  9: CONTRACT, // Project Management
  10: FLEET,   // Asset Management
  11: POWER,   // Quality Management
  12: HR,      // Service Ticketing
  13: CONTRACT, // Document Management
  14: POWER,   // BI
  15: RETAIL,  // E-Commerce
  16: POWER,   // Manufacturing Industry
  17: RETAIL,  // Retail & Distribution
  18: HR,      // Healthcare
  19: HR,      // Education
  20: PROPERTY, // Hospitality
  21: PROPERTY, // Real Estate
  22: FLEET,   // Logistics
  23: POWER,   // Pharma
  24: POWER,   // Textile
  25: RETAIL,  // F&B
  26: POWER,   // IT Industry
};

const img = (id: number) => HERO[id] ?? POWER;

export const MOCK_SOLUTIONS: Solution[] = [
  {
    id: 1,
    slug: 'financial-management',
    category: 'module',
    iconKey: 'wallet',
    title: 'Financial Management',
    tagline: 'A general ledger that finally feels like one source of truth.',
    description:
      'Run a multi-entity, multi-currency, multi-book general ledger from a single console. Close faster, audit cleaner, and stop reconciling the same number across three spreadsheets.',
    features: [
      'Multi-entity, multi-currency general ledger',
      'Accounts payable & receivable with automated matching',
      'Bank reconciliation with rules engine',
      'Cash-flow forecasting up to 18 months out',
      'Budget vs. actual with department drill-down',
      'Tax compliance: VAT, GST, regional sales tax templates',
      'Fixed asset depreciation with multiple methods',
      'Audit trail on every journal line',
      'Period-close checklist with role-based sign-off',
      'Export to Excel, PDF, XBRL',
    ],
    benefits: [
      'Cut month-end close from 9 days to 3',
      'Eliminate manual reconciliation across entities',
      'Always-current cash position visible to leadership',
    ],
    heroImage: img(1),
    relatedIds: [14, 4, 10],
    pricePerSeat: 18,
  },
  {
    id: 2,
    slug: 'inventory-management',
    category: 'module',
    iconKey: 'boxes',
    title: 'Inventory Management',
    tagline: 'Real-time stock visibility — across every warehouse, every channel.',
    description:
      'Know what you have, where, and what it cost — at every moment. Connected to procurement, sales and manufacturing so the number on the screen always matches the bin.',
    features: [
      'Real-time stock levels across multiple warehouses',
      'Lot, batch, and serial number tracking',
      'FIFO / LIFO / weighted-average costing',
      'Min/max reorder rules with automated PR generation',
      'Cycle counts and stock-take with mobile scanning',
      'Bin-level location management',
      'Stock transfers with in-transit tracking',
      'Expiry / shelf-life alerts',
      'Damage & shrinkage write-offs with audit',
      'Barcode + QR generation',
    ],
    benefits: [
      'Reduce carrying costs by 18–24% on average',
      'Cut stockouts and overstocks in half',
      'Stop the spreadsheet-based stock-take cycle',
    ],
    heroImage: img(2),
    relatedIds: [6, 4, 5],
    pricePerSeat: 16,
  },
  {
    id: 3,
    slug: 'sales-distribution',
    category: 'module',
    iconKey: 'trending-up',
    title: 'Sales & Distribution',
    tagline: 'From quote to cash, on a single timeline.',
    description:
      'Quotation, order, dispatch, invoice and collection — every step on one screen, visible to every team that needs it. Sales reps stop chasing finance; finance stops chasing warehouse.',
    features: [
      'Quotations with version history and approval flow',
      'Sales order management with credit-limit checks',
      'Pricing engine: tiered, customer-specific, promotional',
      'Auto-generated invoices on dispatch confirmation',
      'Backorders and partial fulfillment',
      'Returns (RMA) with credit-note automation',
      'Commissions calculation per rep / team',
      'Sales pipeline integration with CRM',
      'Multi-channel: B2B portal, retail POS, e-commerce',
      'Geographic and segment-level analytics',
    ],
    benefits: [
      'Reduce quote-to-cash cycle by 35%',
      'End the email-chain order approval workflow',
      'See live sales performance per rep, per region',
    ],
    heroImage: img(3),
    relatedIds: [8, 1, 15],
    pricePerSeat: 22,
  },
  {
    id: 4,
    slug: 'purchase-procurement',
    category: 'module',
    iconKey: 'shopping-bag',
    title: 'Purchase & Procurement',
    tagline: 'Buy smarter — with a paper trail your auditors will love.',
    description:
      'Manage every purchase from requisition to payment. Vendor scoring, RFQ workflows, three-way matching and approval routing — all configurable without a developer.',
    features: [
      'Purchase requisitions with multi-tier approval',
      'RFQ generation and side-by-side bid comparison',
      'Vendor master with performance scoring',
      'Three-way matching: PO, GRN, invoice',
      'Blanket POs and contract pricing',
      'Drop-ship, consignment, and standard PO types',
      'Vendor portal for self-service quote/PO/invoice',
      'Goods Received Notes (GRN) with quality holds',
      'Spend analytics by category, vendor, department',
      'Automated payment scheduling',
    ],
    benefits: [
      'Identify maverick spend within the first month',
      'Cut PO cycle time from days to hours',
      'Surface cost-saving opportunities through analytics',
    ],
    heroImage: img(4),
    relatedIds: [2, 1, 5],
    pricePerSeat: 18,
  },
  {
    id: 5,
    slug: 'manufacturing-production',
    category: 'module',
    iconKey: 'factory',
    title: 'Manufacturing & Production',
    tagline: 'Plan, schedule, and run the shop floor without spreadsheets.',
    description:
      'A production module that handles discrete, process and mixed-mode manufacturing. BOM versions, work-order routing, real-time WIP — every shift, every line, every yield.',
    features: [
      'Bills of Materials (BOM) with version control',
      'Multi-level routing and operation sequencing',
      'MRP (Material Requirements Planning) and MPS',
      'Work order management with shop-floor terminals',
      'Capacity planning and machine scheduling',
      'Real-time WIP and yield reporting',
      'Subcontracting with vendor batch tracking',
      'Quality holds tied to manufacturing operations',
      'Scrap and rework tracking with root-cause coding',
      'OEE (Overall Equipment Effectiveness) dashboards',
    ],
    benefits: [
      'Increase throughput visibility across shifts',
      'Reduce material waste with tighter BOM control',
      'Predict delivery dates with confidence',
    ],
    heroImage: img(5),
    relatedIds: [2, 11, 16],
    pricePerSeat: 28,
  },
  {
    id: 6,
    slug: 'warehouse-management',
    category: 'module',
    iconKey: 'warehouse',
    title: 'Warehouse Management',
    tagline: 'Floor-level control of every pick, pack and putaway.',
    description:
      'A WMS that runs on the warehouse floor — wave picking, slotting optimisation, mobile scanning, and live KPIs for every shift supervisor.',
    features: [
      'Directed putaway and dynamic slotting',
      'Wave, batch, and zone picking strategies',
      'Mobile barcode scanning (Android / iOS)',
      'Cross-docking and break-bulk operations',
      'Cycle count programs with variance tracking',
      'Pick face replenishment automation',
      'Carrier integration with rate-shopping',
      'License plate and pallet tracking',
      'Returns processing with disposition rules',
      'Live dashboards: pick rate, dock-to-stock, accuracy',
    ],
    benefits: [
      'Improve pick accuracy to 99.7%+',
      'Cut training time for new pickers in half',
      'Free supervisors from clipboard and walkie-talkie',
    ],
    heroImage: img(6),
    relatedIds: [2, 4, 22],
    pricePerSeat: 24,
  },
  {
    id: 7,
    slug: 'hr-payroll',
    category: 'module',
    iconKey: 'users-2',
    title: 'HR & Payroll',
    tagline: 'Pay everyone correctly, on time, the first time.',
    description:
      'TenxERP HR & Payroll enables accurate and efficient processing of employee compensation, ensuring compliance with legal and regulatory requirements. Self-service empowers employees to manage their own information — pay stubs, time-off requests, personal details.',
    features: [
      'Payroll Processing and Reporting — streamlined paychecks and reports',
      'Personnel Record Management — centralised employee data',
      'Workforce Analysis — productivity and utilisation insights',
      'Multi-Organization Support — manage HR across multiple entities',
      'Web-Based and Web-Enabled — secure access from anywhere',
      'SMS and Email Integration — automated employee communications',
      'Export to Excel, Word, PDF — effortless data sharing',
      'Self-service portal: pay stubs, leave, personal details',
      'Attendance with biometric and mobile check-in',
      'Tax and statutory compliance: localised by country',
      'Performance reviews and goal tracking',
      'Onboarding workflows with document collection',
    ],
    benefits: [
      'Eliminate payroll errors that erode employee trust',
      'Cut HR administrative load by half',
      'Give every employee a self-service portal',
    ],
    heroImage: img(7),
    relatedIds: [9, 13, 26],
    pricePerSeat: 14,
  },
  {
    id: 8,
    slug: 'crm',
    category: 'module',
    iconKey: 'heart-handshake',
    title: 'Customer Relationship Management',
    tagline: 'A CRM that finally talks to the rest of your business.',
    description:
      'Lead capture, opportunity management, customer history and sales forecasting — natively connected to inventory, sales orders, invoicing and support tickets.',
    features: [
      'Lead management with auto-assignment and SLA',
      'Account and contact 360° view — every order, ticket, email',
      'Opportunity pipeline with weighted forecasting',
      'Quote and proposal generation from opportunities',
      'Email integration: Gmail, Outlook, IMAP',
      'Activity timeline: calls, emails, meetings, notes',
      'Marketing campaign tracking with attribution',
      'Customer segmentation and saved views',
      'Mobile app for field sales teams',
      'Lead scoring with custom rules',
    ],
    benefits: [
      'Stop losing context between sales and support',
      'Forecast revenue with grounded confidence',
      'Give field reps everything they need on mobile',
    ],
    heroImage: img(8),
    relatedIds: [3, 12, 9],
    pricePerSeat: 20,
  },
  {
    id: 9,
    slug: 'project-management',
    category: 'module',
    iconKey: 'kanban',
    title: 'Project Management',
    tagline: 'For services teams that bill by the hour and deliver by the day.',
    description:
      'Plan projects, allocate resources, capture time, bill clients — and roll every hour straight into the GL. Built for IT services, agencies, consultancies, construction.',
    features: [
      'Gantt and Kanban views with dependencies',
      'Resource allocation with skill matching',
      'Timesheets with mobile entry and approval',
      'Project budgets with EVM (earned value management)',
      'Milestone-based and time-and-materials billing',
      'Project P&L with real-time cost tracking',
      'Client portal for status and approvals',
      'Document and file management per project',
      'Risk and issue logs',
      'Resource utilisation heatmaps',
    ],
    benefits: [
      'See project profitability the moment it slips',
      'Free PMs from spreadsheet status reports',
      'Bill clients with detail that prevents disputes',
    ],
    heroImage: img(9),
    relatedIds: [7, 8, 26],
    pricePerSeat: 19,
  },
  {
    id: 10,
    slug: 'asset-management',
    category: 'module',
    iconKey: 'building',
    title: 'Asset Management',
    tagline: 'Every asset, its lifecycle, its cost — tracked from purchase to disposal.',
    description:
      'Track fixed assets, IT equipment, vehicles and machinery from acquisition through depreciation to disposal. Maintenance schedules, warranty alerts, transfer history.',
    features: [
      'Asset register with categories, tags, custodians',
      'Multiple depreciation methods per asset class',
      'Preventive maintenance schedules',
      'Service history and cost-per-asset reporting',
      'Asset transfers between locations / departments',
      'Warranty tracking with renewal alerts',
      'Disposal workflow with gain/loss calculation',
      'QR / RFID tagging support',
      'Mobile asset audits',
      'Insurance and licence renewal reminders',
    ],
    benefits: [
      'Surprise audits become a non-event',
      'Stop paying for warranties on disposed assets',
      'Know your true cost of ownership per asset class',
    ],
    heroImage: img(10),
    relatedIds: [1, 11, 21],
    pricePerSeat: 12,
  },
  {
    id: 11,
    slug: 'quality-management',
    category: 'module',
    iconKey: 'shield-check',
    title: 'Quality Management',
    tagline: 'Pass audits without scrambling for evidence.',
    description:
      'Inspections, NCRs, CAPAs, supplier quality, and document control — every quality event linked to the order, batch or asset that produced it.',
    features: [
      'Inspection plans for incoming, in-process, final',
      'Non-conformance reports (NCR) with workflow',
      'CAPA (corrective and preventive actions) tracking',
      'Statistical process control (SPC) charts',
      'Supplier quality scorecards',
      'Document control with versioning + sign-off',
      'Audit management: internal, supplier, regulatory',
      'Calibration scheduling and history',
      'Training records linked to procedures',
      'ISO 9001 / 13485 / 22000 ready templates',
    ],
    benefits: [
      'Sail through ISO audits with evidence on tap',
      'Quantify the cost of poor quality',
      'Close the loop on every customer complaint',
    ],
    heroImage: img(11),
    relatedIds: [5, 16, 23],
    pricePerSeat: 22,
  },
  {
    id: 12,
    slug: 'service-ticketing',
    category: 'module',
    iconKey: 'life-buoy',
    title: 'Service Ticketing',
    tagline: 'Service desk and field service in one.',
    description:
      'A unified ticketing system that handles internal helpdesk, customer support, on-site field service and SLAs — connected to assets, contracts and CRM.',
    features: [
      'Multi-channel ticket capture: email, portal, chat, phone',
      'SLA management with breach alerts',
      'Ticket categorisation and auto-routing',
      'Knowledge base with article suggestions',
      'Field service: dispatch, route optimisation, mobile app',
      'Asset-linked tickets with full service history',
      'Contract management with covered services',
      'Customer satisfaction (CSAT) surveys',
      'Time tracking on tickets for billing',
      'Escalation matrix with on-call rotations',
    ],
    benefits: [
      'Resolve faster with full asset and customer context',
      'Stop missing SLAs you didn\'t know existed',
      'Equip field techs with a single mobile app',
    ],
    heroImage: img(12),
    relatedIds: [8, 26, 10],
    pricePerSeat: 16,
  },
  {
    id: 13,
    slug: 'document-management',
    category: 'module',
    iconKey: 'folder-open',
    title: 'Document Management',
    tagline: 'Find any document in three keystrokes.',
    description:
      'Centralised document repository with versioning, OCR, role-based access, and approval workflows — woven into every other module so documents live where the work does.',
    features: [
      'Folder hierarchy with role-based permissions',
      'OCR on uploaded PDFs and images',
      'Full-text search across all documents',
      'Version history with diff view',
      'E-signature integration',
      'Approval workflows with deadlines',
      'Document templates with merge fields',
      'Watermarking and download protection',
      'Retention policies with auto-archive',
      'Audit log of every view, download, edit',
    ],
    benefits: [
      'End the "where\'s the latest version?" email thread',
      'Comply with retention policies without thinking',
      'Onboard new hires with documents that find themselves',
    ],
    heroImage: img(13),
    relatedIds: [7, 11, 1],
    pricePerSeat: 9,
  },
  {
    id: 14,
    slug: 'business-intelligence',
    category: 'module',
    iconKey: 'bar-chart-3',
    title: 'Business Intelligence',
    tagline: 'Dashboards your CFO will actually open.',
    description:
      'Pre-built dashboards for every module, plus a drag-and-drop report builder. Drill from a P&L line down to the journal entry that produced it.',
    features: [
      'Pre-built dashboards: finance, sales, operations, HR',
      'Drag-and-drop report builder',
      'Drill-down from KPI to source transaction',
      'Scheduled report delivery (email, Slack, Teams)',
      'Cross-module pivots and joins',
      'Conditional formatting and alerts',
      'Export to Excel, PDF, CSV, Power BI',
      'Custom calculated metrics',
      'Role-based dashboard publishing',
      'Mobile-first dashboard experience',
    ],
    benefits: [
      'Replace three BI tools with one',
      'Give every executive a personalised cockpit',
      'Stop emailing weekly reports — they subscribe',
    ],
    heroImage: img(14),
    relatedIds: [1, 3, 5],
    pricePerSeat: 24,
  },
  {
    id: 15,
    slug: 'ecommerce-integration',
    category: 'module',
    iconKey: 'shopping-cart',
    title: 'E-Commerce Integration',
    tagline: 'Your storefront and your back office, finally on speaking terms.',
    description:
      'Native connectors for Shopify, WooCommerce, Magento and custom storefronts — orders, inventory, customers and pricing sync in real time.',
    features: [
      'Native Shopify, WooCommerce, Magento connectors',
      'Real-time inventory sync to all channels',
      'Order import with automatic GL posting',
      'Customer master sync with deduplication',
      'Pricing and promo synchronisation',
      'Returns and refunds across channels',
      'Marketplace integrations: Amazon, Daraz, Noon',
      'Channel-specific catalog management',
      'Tax handling per region',
      'Abandoned-cart recovery analytics',
    ],
    benefits: [
      'Sell on five channels without overselling on any',
      'Onboard new marketplaces in days, not months',
      'See total customer LTV across every channel',
    ],
    heroImage: img(15),
    relatedIds: [3, 2, 8],
    pricePerSeat: 20,
  },
  {
    id: 16,
    slug: 'manufacturing-industry',
    category: 'industry',
    iconKey: 'cog',
    title: 'Manufacturing Industry',
    tagline: 'Discrete, process and mixed-mode — under one roof.',
    description:
      'A pre-configured TenxERP deployment for manufacturers: BOMs, work orders, MRP, quality holds, costing, traceability — set up the way your industry actually works.',
    features: [
      'Pre-configured BOM and routing templates',
      'MRP run with what-if scenario planning',
      'Lot and serial traceability end-to-end',
      'Standard, actual and average costing',
      'Subcontracting and toll manufacturing flows',
      'Production scheduling with finite capacity',
      'Quality plans tied to operations',
      'Industry-standard reports: yield, OEE, scrap',
      'EDI integration with major customers',
      'Compliance: ISO 9001, AS9100, IATF 16949',
    ],
    benefits: [
      'Go live in 8–12 weeks instead of 18 months',
      'Inherit a chart of accounts your auditors recognise',
      'Use reports that mean something to your shop floor',
    ],
    heroImage: img(16),
    relatedIds: [5, 11, 6],
    pricePerSeat: 32,
  },
  {
    id: 17,
    slug: 'retail-distribution',
    category: 'industry',
    iconKey: 'store',
    title: 'Retail & Distribution',
    tagline: 'Multi-store, multi-channel, single-source-of-truth.',
    description:
      'Run dozens of stores, multiple online channels and a distribution centre — all on one system. Promotions, loyalty, inventory and finance, integrated.',
    features: [
      'POS for in-store with offline-first capability',
      'Promotions engine: BOGO, tiered, basket-level',
      'Loyalty program with tiered rewards',
      'Multi-store inventory with intelligent transfers',
      'E-commerce sync (omnichannel)',
      'Customer 360° including in-store + online',
      'Markdown management',
      'Vendor managed inventory (VMI)',
      'Replenishment forecasting per store',
      'Daily sales close per store',
    ],
    benefits: [
      'Lower stock-outs without raising carrying cost',
      'Run promotions across all channels in minutes',
      'See store-level P&L the morning after close',
    ],
    heroImage: img(17),
    relatedIds: [3, 2, 15],
    pricePerSeat: 26,
  },
  {
    id: 18,
    slug: 'healthcare',
    category: 'industry',
    iconKey: 'stethoscope',
    title: 'Healthcare',
    tagline: 'Hospitals and clinics, run with the discipline of a factory and the warmth of a pharmacy.',
    description:
      'A vertical configured for healthcare: patient billing, pharmacy inventory with expiry, lab integration, insurance claims, payroll for doctors and nurses.',
    features: [
      'Patient registration and admissions',
      'Outpatient, inpatient and emergency billing',
      'Pharmacy with batch + expiry + cold-chain tracking',
      'Insurance claim management with EDI',
      'Lab integration with LIS interfaces',
      'Doctor scheduling and consultation fees',
      'Nursing duty rosters',
      'Medical asset and equipment maintenance',
      'HIPAA-aligned audit trails',
      'Multi-facility consolidation',
    ],
    benefits: [
      'Cut billing errors and claim rejections',
      'Eliminate expired-stock write-offs',
      'Give doctors a calmer back-office',
    ],
    heroImage: img(18),
    relatedIds: [1, 7, 23],
    pricePerSeat: 30,
  },
  {
    id: 19,
    slug: 'education',
    category: 'industry',
    iconKey: 'graduation-cap',
    title: 'Education',
    tagline: 'Schools and universities — admissions to alumni.',
    description:
      'Student information, fee management, hostel, transport, examinations, payroll, library — a single platform for institutions from K-12 to research universities.',
    features: [
      'Admissions with online application portal',
      'Student information system (SIS)',
      'Fee billing with installments and scholarships',
      'Examination, grading and transcripts',
      'Hostel and transport management',
      'Library with circulation and reservations',
      'Faculty payroll and load tracking',
      'Parent / guardian portal',
      'Alumni database',
      'Government / regulatory reporting',
    ],
    benefits: [
      'Admissions and registration without the queues',
      'Fee defaults visible the day they happen',
      'One login for parents, students and staff',
    ],
    heroImage: img(19),
    relatedIds: [7, 13, 1],
    pricePerSeat: 14,
  },
  {
    id: 20,
    slug: 'hospitality',
    category: 'industry',
    iconKey: 'hotel',
    title: 'Hospitality',
    tagline: 'Hotels, resorts and restaurants — front desk to back office.',
    description:
      'Property management (PMS), POS, F&B inventory, banquet & event, housekeeping, channel manager and accounting — engineered for hospitality.',
    features: [
      'PMS: reservations, check-in/out, group bookings',
      'Channel manager: OTA inventory + rates',
      'Restaurant & bar POS',
      'Banquet and event management',
      'F&B recipe and beverage costing',
      'Housekeeping with mobile updates',
      'Concierge and guest service tracking',
      'Loyalty + guest history across properties',
      'Night audit automation',
      'Group P&L per property',
    ],
    benefits: [
      'Cut night-audit time by 80%',
      'Stop OTA-channel overbooking',
      'See cost-per-cover by restaurant, by daypart',
    ],
    heroImage: img(20),
    relatedIds: [3, 2, 17],
    pricePerSeat: 24,
  },
  {
    id: 21,
    slug: 'real-estate-construction',
    category: 'industry',
    iconKey: 'hard-hat',
    title: 'Real Estate & Construction',
    tagline: 'Projects, units, tenants — and the cash that flows between them.',
    description:
      'Project costing, unit-level inventory, lease management, recurring billing, contractor management and progress billing — for builders, developers and property managers.',
    features: [
      'Project budgeting with cost codes',
      'Unit inventory: residential / commercial',
      'Sales contracts with installment plans',
      'Tenant lease management with auto-renewals',
      'Recurring rental billing',
      'Subcontractor management with payment certificates',
      'Progress billing tied to milestones',
      'Material requisition from project budgets',
      'Quantity surveys and BOQ',
      'Maintenance for managed properties',
    ],
    benefits: [
      'Know which units, leases, projects are profitable',
      'Stop chasing rent with manual reminders',
      'Bill clients by completion, not by guesswork',
    ],
    heroImage: img(21),
    relatedIds: [9, 4, 10],
    pricePerSeat: 28,
  },
  {
    id: 22,
    slug: 'logistics-transportation',
    category: 'industry',
    iconKey: 'truck',
    title: 'Logistics & Transportation',
    tagline: 'Fleet, freight, fuel — and the cost of every kilometre.',
    description:
      'Fleet management, dispatching, freight billing, driver payroll, fuel tracking, vehicle maintenance — built for 3PLs, hauliers and last-mile operators.',
    features: [
      'Fleet master with documents and renewals',
      'Trip planning and dispatching',
      'Freight billing per shipment / contract',
      'Driver payroll with trip allowances',
      'Fuel cards and consumption tracking',
      'Vehicle maintenance and inspection',
      'GPS / telematics integration',
      'Customer portal with shipment tracking',
      'Subcontracted carrier management',
      'Cost-per-km / ton-km analytics',
    ],
    benefits: [
      'Identify trips that lose money',
      'Slash fuel pilferage with consumption analysis',
      'Give customers self-service tracking',
    ],
    heroImage: img(22),
    relatedIds: [6, 4, 10],
    pricePerSeat: 22,
  },
  {
    id: 23,
    slug: 'pharmaceuticals',
    category: 'industry',
    iconKey: 'pill',
    title: 'Pharmaceuticals',
    tagline: 'GxP-ready ERP for pharma manufacturers and distributors.',
    description:
      'Batch manufacturing records, regulatory compliance, expiry and recall management, controlled substances tracking — designed for pharma operations.',
    features: [
      'Electronic batch manufacturing records (eBMR)',
      'GxP and 21 CFR Part 11 audit support',
      'Lot and expiry tracking with FEFO picking',
      'Recall and quarantine management',
      'Controlled substances register',
      'Stability study tracking',
      'Cold-chain monitoring integration',
      'Regulatory submissions document control',
      'Vendor qualification workflows',
      'Multi-country regulatory templates',
    ],
    benefits: [
      'Pass FDA / DRAP / EMA inspections with confidence',
      'Recall a batch in minutes, not days',
      'Reduce expiry-driven write-offs structurally',
    ],
    heroImage: img(23),
    relatedIds: [11, 5, 18],
    pricePerSeat: 36,
  },
  {
    id: 24,
    slug: 'textile',
    category: 'industry',
    iconKey: 'shirt',
    title: 'Textile Industry',
    tagline: 'Greige to garment — every yard tracked.',
    description:
      'Spinning, weaving, dyeing, knitting, garmenting — TenxERP supports every textile process with industry-specific BOMs, costing and quality.',
    features: [
      'Yarn / fabric / garment BOMs',
      'Lot-based inventory: dye lot, shade band',
      'Greige, finished, dispatched stock',
      'Process-wise costing and yield',
      'Loom / knitting machine scheduling',
      'Embroidery and printing subcontract',
      'Garment cutting plan optimisation',
      'Color and quality matching',
      'Export documentation and shipment',
      'Compliance: BSCI, SEDEX, WRAP',
    ],
    benefits: [
      'Cost garments correctly across shade bands',
      'Reduce fabric waste at cutting stage',
      'Run export documentation without translation errors',
    ],
    heroImage: img(24),
    relatedIds: [5, 11, 22],
    pricePerSeat: 30,
  },
  {
    id: 25,
    slug: 'food-beverage',
    category: 'industry',
    iconKey: 'utensils-crossed',
    title: 'Food & Beverage',
    tagline: 'Recipes, batches, expiries — and the margin on every plate.',
    description:
      'Recipe management, batch tracking, allergen control, sales analytics by item / daypart, food cost tracking — for QSR, casual dining, central kitchens and packaged food manufacturers.',
    features: [
      'Recipes with cost rollup and yield',
      'Allergen and nutrition information',
      'Batch traceability (one-up / one-down)',
      'Central kitchen → outlet stock transfers',
      'Wastage and spoilage tracking',
      'POS integration with daypart analytics',
      'Menu engineering: stars, plowhorses, dogs',
      'Recipe cost simulation',
      'Hygiene and HACCP compliance',
      'Supplier quality scoring',
    ],
    benefits: [
      'Know your true plate cost',
      'Recall affected batches in minutes',
      'Cut food waste with daypart-level forecasting',
    ],
    heroImage: img(25),
    relatedIds: [11, 17, 6],
    pricePerSeat: 22,
  },
  {
    id: 26,
    slug: 'it-industry',
    category: 'industry',
    iconKey: 'cpu',
    title: 'IT Industry',
    tagline: 'ERP designed for software companies, IT services and consultancies.',
    description:
      'TenxERP for the IT industry streamlines operations across software development, IT consulting, cybersecurity, and managed services. Manage projects, allocate resources, capture finance, run service desks — all on one platform built for how IT companies actually work.',
    features: [
      'Project & Resource Management — manage complex projects, allocate resources, track progress in real time',
      'Finance Management — capture project costs accurately, track expenses, generate precise invoices',
      'Contracts Management — contract creation, negotiation, milestone tracking, compliance',
      'Service Ticketing — handle inquiries, incidents and service requests with SLAs',
      'ITSM & CRM Integration — centralised customer interaction and sales tracking',
      'Skill matrix and resource utilisation heatmaps',
      'Time and material vs. fixed-price billing',
      'Recurring revenue tracking for SaaS / managed services',
      'Subcontractor and partner management',
      'Client portal with project, invoice and ticket access',
    ],
    benefits: [
      'Optimise utilisation across consultants and engineers',
      'Bill clients accurately for time and materials',
      'Deliver exceptional support with full asset and contract context',
    ],
    heroImage: img(26),
    relatedIds: [9, 8, 12],
    pricePerSeat: 26,
  },
];
